### ISSUE TITLE
Закройте репозиторий

### ISSUE THREAD

**Issue by Kalstro** [Norrica/NewPythonCourse#18]
Скрипты с уроков ссылку на которые практически напрямую дают ученикам это может быть не очень хорошо.

**Comment by Norrica** [comment]
При обнаружении(очень легком) несанкционированных изменений в репозитории, откатить и закрыть его будет вопросом легким. На время разработки было принято решение оставить открытым. Не вижу, как именно это может быть не очень хорошо.
